name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Odin
        uses: laytan/setup-odin@v2
        with:
          release: false

      - name: Run test.bat
        run: |
          call odin test tests -all-packages -debug
