name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone Odin
        run: |
          git clone --recursive https://github.com/odin-lang/Odin

      - name: Set up Odin (Windows)
        if: runner.os == 'Windows'
        run: |
          cd Odin
          build.bat release

      - name: Set up Odin (Linux)
        if: runner.os != 'Windows'
        run: |
          cd Odin
          build_odin.sh release

      - name: Run tests /Windows
        if: runner.os == 'Windows'
        run: |
          call Odin/odin.exe test tests -all-packages -debug

      - name: Run tests (Linux)
        if: runner.os != 'Windows'
        run: |
          ./Odin/odin test tests -all-packages -debug
